name: 🚀 FTP Deploy - MAIN

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📂 Upload changed files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/domains/karstejn.cz/
          local-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/node_modules/**
            storage/**
            .env
