on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  deploy-master:
    name: "main branch"
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "ftp"
          remote-host: "365139.w39.wedos.net"
          remote-user: "w365139_janekvodicka"
          ssh-private-key: ${{ secrets.ftp_password }}
          remote-path: "/www/domains/zkouska.karstejn.cz"
