name: Deploy via FTP
on:
  push:
    branches:
      - test
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4     

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Set environment variables
        run: |
          echo "Setting environment variables based on the branch..."
          if [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "FTP_HOST=${{ secrets.FTP_HOST_TEST }}" >> $GITHUB_ENV
            echo "FTP_USER=${{ secrets.FTP_USER_TEST }}" >> $GITHUB_ENV
            echo "FTP_PASS=${{ secrets.FTP_PASS_TEST }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "FTP_HOST=${{ secrets.FTP_HOST_PROD }}" >> $GITHUB_ENV
            echo "FTP_USER=${{ secrets.FTP_USER_PROD }}" >> $GITHUB_ENV
            echo "FTP_PASS=${{ secrets.FTP_PASS_PROD }}" >> $GITHUB_ENV
          fi
          echo "Environment variables set."

      - name: Deploy to FTP
        uses: BitwaySystem/git-ftp-sync@v1.0.0
        with:
          ftp_host: ${{ env.FTP_HOST }}
          ftp_user: ${{ env.FTP_USER }}
          ftp_pass: ${{ env.FTP_PASS }}
          branch: ${{ github.ref }}
          extract_path: "/"
