on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 365139.w39.wedos.net
        username: w365139_janekvodicka
        password: ${{ secrets.ftp_password }}
        server-dir: /www/domains/zkouska.karstejn.cz/
        timeout: 60000
